<a href="https://colab.research.google.com/github/EmilyMesias/EMILY/blob/main/emilymesias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#create an array with random inteher values between 1 and 10
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('Adding numbers')
#plus
print(a+b)
print('Subtracting numbers')
#minus
print(a-b)
print('Multiplication numbers')
#times
print(a*b)


print('Add')
print(np.add(a,b))
print('Substract')
print(np.multiply(a,b))
print('Multiply')
print(np.subtract(a,b))
print('Divide')
print(np.divide(a,b))


[[ 4 10  7  7]
 [ 8  2  2  4]
 [ 8  4  4  3]]
[[ 8  9  1  4]
 [10  5  2  5]
 [ 6  3  4  2]]
(3, 4)
(3, 4)
Adding numbers
[[12 19  8 11]
 [18  7  4  9]
 [14  7  8  5]]
Subtracting numbers
[[-4  1  6  3]
 [-2 -3  0 -1]
 [ 2  1  0  1]]
Multiplication numbers
[[32 90  7 28]
 [80 10  4 20]
 [48 12 16  6]]
Add
[[12 19  8 11]
 [18  7  4  9]
 [14  7  8  5]]
Substract
[[32 90  7 28]
 [80 10  4 20]
 [48 12 16  6]]
Multiply
[[-4  1  6  3]
 [-2 -3  0 -1]
 [ 2  1  0  1]]
Divide
[[0.5        1.11111111 7.         1.75      ]
 [0.8        0.4        1.         0.8       ]
 [1.33333333 1.33333333 1.         1.5       ]]


In [2]:
m1 = np.random.randint(1, 11, size=(3,4))
m2 = np.random.randint(1, 11, size=(4,8))
print('Matriz 1')
print(m1)
print(m1.shape)
print('Matriz 2')
print(m2)
print(m2.shape)
print('-------------------------')
print('Forma 1')
print(np.dot(m1,m2))
print('Forma 2')
print(m1.dot(m2))
print(np.dot(m1,m2).shape)

Matriz 1
[[ 3  2  4  3]
 [ 4  2  4  5]
 [10  2  9  3]]
(3, 4)
Matriz 2
[[ 8  3  7  2  2  7  1 10]
 [ 7  7  4  2  3 10  1  3]
 [ 1  5 10  8  3  2  3  7]
 [ 8  5  5 10  7  7 10  8]]
(4, 8)
-------------------------
Forma 1
[[ 66  58  84  72  45  70  47  88]
 [ 90  71 101  94  61  91  68 114]
 [127 104 183 126  74 129  69 193]]
Forma 2
[[ 66  58  84  72  45  70  47  88]
 [ 90  71 101  94  61  91  68 114]
 [127 104 183 126  74 129  69 193]]
(3, 8)


In [3]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)


(2, 2)
<class 'numpy.ndarray'>
[[1 4]
 [7 1]]
[[1 7]
 [4 1]]


In [4]:
#broadcast
x = np.random.randint(1, 11, size=(4,3))
y = np.array([1,0,2])

print(x.shape)
print(y.shape)

z=np.empty_like(x)
print('---------------------')
print(x)
print('---------------------')
print(y)
print(z.shape)
print('---------------------')
print(z)


(4, 3)
(3,)
---------------------
[[ 7  3  4]
 [10  7  9]
 [10  3  3]
 [ 3  3  2]]
---------------------
[1 0 2]
(4, 3)
---------------------
[[4602678819172646912 4607682818758614130 4619567317775286272]
 [4610560118520545280 4605380978949069210 4600877379321698714]
 [4607182418800017408 4605380978949069210 4608683618675807573]
 [4608683618675807573 4607182418800017408 4609434218613702656]]


In [5]:
for i in range(4):
  z[i,:]=x[i,:]+y
print(z)

[[ 8  3  6]
 [11  7 11]
 [11  3  5]
 [ 4  3  4]]


In [6]:
z=x+y
print(z)


[[ 8  3  6]
 [11  7 11]
 [11  3  5]
 [ 4  3  4]]


In [7]:
#para comentar varias lineas de codigo se usa triple comillas simples """  """

a=np.array([1,2,3])
print(a)
print('-----------------')

b = np.full((6,3),[a])
print(b)
print('-----------------')

c= np.tile(a,(6,1))
print(c)

[1 2 3]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
-----------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
m1 = np.random.randint(0, 10, size=(6,6))
print(m1)
aux=np.mean(m1)
print(aux)

np.mean(m1, axis=1) #promedio por filas
np.mean(m1, axis=0) #promedio por filas

print('Promedio por filas')
print(np.mean(m1, axis=1))
print('Promedio por columnas')
print(np.mean(m1, axis=0))

[[9 2 0 6 3 8]
 [8 0 7 1 7 7]
 [9 6 7 8 6 9]
 [0 7 3 8 4 9]
 [1 6 8 1 3 7]
 [3 0 6 0 1 2]]
4.777777777777778
Promedio por filas
[4.66666667 5.         7.5        5.16666667 4.33333333 2.        ]
Promedio por columnas
[5.         3.5        5.16666667 4.         4.         7.        ]
