<a href="https://colab.research.google.com/github/EmilyMesias/EMILY/blob/main/emily.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as emily

aux=emily.array([1,2,4,5])
print(aux)
# Tipo de arreglo
print(aux.shape)
print('------------------------------')

aux=emily.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print('------------------------------')

tmp=emily.zeros((4,4))
print(tmp)
print('------------------------------')


tmp=emily.full((4,4),5)
print(tmp)
print('------------------------------')


tmp=emily.eye(4,4)
print(tmp)
print('------------------------------')


tmp=emily.ones((4,4))
print(tmp)
print('------------------------------')


[1 2 4 5]
(4,)
------------------------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
------------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
------------------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------------------


In [5]:
tmp=10*emily.random.random((4,4))
print(tmp)
print('------------------------------')


[[8.38462044 2.96265783 6.99668871 9.14253721]
 [0.41877271 6.8935025  0.69708977 3.30891262]
 [9.85313512 3.09427088 2.26161119 2.71699944]
 [1.57067966 1.76016252 7.22097921 1.45816747]]
------------------------------


In [6]:
print(tmp[:2,:2])
print('------------------------------')
print(tmp[2:4,2:4])


[[8.38462044 2.96265783]
 [0.41877271 6.8935025 ]]
------------------------------
[[2.26161119 2.71699944]
 [7.22097921 1.45816747]]


In [7]:
print(tmp[1,1])
print('------------------------------')
print(tmp[2,2])
print('------------------------------')


6.893502497688077
------------------------------
2.2616111869268716
------------------------------


In [8]:
tmp=10*emily.random.random((4,4))
print(tmp)

[[9.28433143 1.84668595 3.49684665 4.06459918]
 [2.49442839 6.96877715 0.61714687 6.78956486]
 [9.11559401 3.0654718  0.21525673 3.46944459]
 [2.91539062 3.01973414 2.93179706 0.08692208]]


In [9]:
mascara=tmp>5
print(mascara)
print('------------------------------')
print(tmp[mascara])
print('------------------------------')

[[ True False False False]
 [False  True False  True]
 [ True False False False]
 [False False False False]]
------------------------------
[9.28433143 6.96877715 6.78956486 9.11559401]
------------------------------


In [10]:
mask = (tmp >=2) & (tmp<=4)
print(tmp[mask])

[3.49684665 2.49442839 3.0654718  3.46944459 2.91539062 3.01973414
 2.93179706]


In [11]:
tmp = emily.random.randint(0, 11, size=(4, 4))
print(tmp)
print('----------------------------------')
mask = emily.mod(tmp, 2) == 0
print(tmp[mask])

[[7 7 2 7]
 [6 5 6 6]
 [9 3 0 8]
 [3 2 5 0]]
----------------------------------
[2 6 6 6 0 8 2 0]
